# Set Site Details
site_name: "Open Source Rails"
site_url: "http://www.opensourcerails.com"
version: "v0.5"
require_email_activation: true

# SEO Stuff
default_meta_keywords: "open source ruby on rails"
default_meta_description: "Open Source Rails is a community site dedicated to tracking the best open source Ruby on Rails applications."

# Paging Sizes
projects_per_page: 6

# Set Avatar Sizes
screenshot_sizes: 
  medium: "225x225#"
  thumb: "70x70#"

# Set default avatar
screenshot_default: "/images/default_screenshots/:style.png"